[package]
name = "var"
version = "0.1.0"
authors = ["Lei Zhao <lei.zhao@coupa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.12"
